Added support for new message api endpoints
getzep/zep-python pull request #100
Opened 2023-12-08 18:42 UTC by petergarbers

2023-12-08 19:53 UTC, petergarbers commented on zep_python/message/client.py
> +                    "Both page_size and page_number must be positive integers"
limit and cursor

2023-12-08 19:59 UTC, petergarbers commented on zep_python/message/client.py
> +        url = f"/sessions/{session_id}/messages"
include support ofr limit and cursor

2023-12-08 19:59 UTC, petergarbers commented on zep_python/message/client.py
> +            print(f"url: {url}")
remove me

2023-12-08 20:01 UTC, petergarbers commented on zep_python/message/client.py
> +            print(f"url: {url}")
remove me

2023-12-08 20:05 UTC, petergarbers commented on examples/messages_async.py
> +        user = client.user.add(user_request)
async

2023-12-08 20:08 UTC, petergarbers commented on examples/messages_async.py
> +    client, session_id, first_session_message_id
message_id

2023-12-08 20:10 UTC, petergarbers commented on examples/messages_sync.py
> +    api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.nEJCptN3CRfD_SQ4om4Oa2yh-ARPI41qkjj0La0Hw54"
Put your key here

2023-12-11 19:23 UTC, danielchalef commented
@petergarbers since the new message functionality is reliant on a new server version, we should update the following to `0.21.0`, which will be the next feature release version of Zep. Developers will be warned if using this client with an older version of the Zep server.

https://github.com/getzep/zep-python/blob/be81edcb749adfa4f5b1a436140fb1edc6d86bc6/zep_python/zep_client.py#L25

2023-12-11 19:24 UTC, danielchalef requested changes
see my comment regarding the minimum server version

2023-12-14 18:57 UTC, danielchalef approved these changes
lgtm

2023-12-14 19:03 UTC, merged