...
getzep/zep-python pull request #126
Opened 2024-03-04 20:49 UTC by petergarbers

2024-03-06 16:52 UTC, paul-paliychuk approved these changes

2024-03-06 22:07 UTC, danielchalef requested changes

2024-03-06 22:07 UTC, danielchalef commented on zep_python/message/models.py
> +class RoleType(str, Enum):
the role suffix seems redundant and the capitalization brittle.

2024-03-08 15:45 UTC, danielchalef approved these changes
lgtm

2024-03-08 15:45 UTC, merged