...
getzep/zep-python pull request #139
Opened 2024-03-20 14:36 UTC by paul-paliychuk

2024-03-24 18:43 UTC, danielchalef requested changes

2024-03-24 18:43 UTC, danielchalef commented on zep_python/langchain/history.py
> +        Additional instruction for generating the summary.
```suggestion
        Additional instructions for generating dialog summaries.
```

2024-03-24 18:43 UTC, danielchalef commented on examples/ecommerce-chainlit/app.py
> +            summary_instruction="Omit user shoe size from the summary",
```suggestion
            summary_instruction="Do not include shoe sizes.",
```

2024-03-24 21:45 UTC, danielchalef approved these changes
lgtm

2024-03-26 16:01 UTC, petergarbers approved these changes

2024-03-27 18:46 UTC, merged